### ISSUE TITLE
VR Assets

### ISSUE THREAD

**Issue by JonahJana** [DeltaChrome/w3SurviveD#9]
Environment

- [x] Tree
- [x] Log
- [x] Stick
- [x] Rock
- [x] Leaf
Tools

- [x] Backpack
- [x] Fire bow, rock and stick
- [x] Hammer

Objectives

- [x] Axe
- [x] Fire Pit
- [x] Shelter

**Comment by MmesAmanda** [comment]
Total of 4 different types of low poly trees were created. -W1
